### ISSUE TITLE
pip installできるように

### ISSUE THREAD

**Issue by yu9824** [yu9824/chemical-viewer#1]
`pip install`できるようにして、pyproject.tomlで下記の設定をして、スタンドアロンアプリがインストールさせられるか検証する。

```toml
[project.gui-scripts]
spam-gui = "spam:main_gui"

```
